empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

def DesdeAppDepartamento(self):
    print('###############################Desde la App Departamento######################################' )

app_name = "departamento_app"

urlpatterns = [
    path('departamento/', DesdeAppDepartamento), # Django ejecutara la funcion DesdeAppDepartamento si en el navegador colocamos la cadena 'http://127.0.0.1:8000/departamento/'
    path('new_departamento/', views.NewDepartamentoView.as_view(),name='nuevo_departamento'),
    path('departamento_lista/', views.DepartamentoListView.as_view(),name='departamento_list'),

]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

# def DesdeAppPersona(self):
#     print('###############################Desde la App Persona######################################' )
    
# urlpatterns = [
#     path('persona/', DesdeAppPersona), # Django ejecutara la funcion DesdeAppDepartamento si en el navegador colocamos la cadena 'http://127.0.0.1:8000/persona/'
# ]

from . views import (ListAllEmpleados,ListByArea,ListByJob,
                    ListEmpleadosByKword,ListHabilidadesEmpleado,
                    EmpleadoDetailView,EmpleadoCreateView,
                    SuccessView,EmpleadoUpdateView,
                    EmpleadoDeleteView,
                    InicioView,
                    ListEmpleadosAdmin

)

app_name = "persona_app" # este es una etiqueta para ubicar el bloque urls de la aplicacion persona

urlpatterns = [
    path('',InicioView.as_view(),name='inicio'),
    path('buscar_empleado/', ListEmpleadosByKword.as_view(),name='buscar_empleado'), # Django ejecutara PruebaView(TemplateView) si en el navegador colocamos la cadena 'http://127.0.0.1:8000/prueba/'
    path('listar-todo-empleados/', ListAllEmpleados.as_view(),name='empleados_all'), # Django ejecutara ListAllEmpleados(ListView) si en el navegador colocamos la cadena 'http://127.0.0.1:8000/listar-todo-empleados/'
    path('lista_by_area/<shor_name>/',ListByArea.as_view(),name='empleados_area'),
    path('lista_by_job/',ListByJob.as_view()),
    path('lista_habilidades_empleado/',ListHabilidadesEmpleado.as_view()),
    path('ver_empleado/<pk>/',EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/',EmpleadoCreateView.as_view(), name='empleado_add'),
    # path('success/',SuccessView.as_view()),
    path(
        'success/',SuccessView.as_view(),
        name='correcto'      #con name puedo hacer mencion a la url "/success" desde cualquier success_url
    ),                           
    path('update_empleado/<pk>/',EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('eliminar_empleado/<pk>/',EmpleadoDeleteView.as_view(),name='eliminar_empleado'),
    path('lista_empleados_admin/',ListEmpleadosAdmin.as_view(),name='empleados_admin'),
        
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

    
urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluiremos las urls de la app departamento
    path('', include('applications.departamento.urls')), # Django incluye las diferentes urls declaradas en applications.departamento.urls.py a 'http://127.0.0.1:8000/XXXXXXXX/'
    path('', include('applications.persona.urls')), # Django incluye las diferentes urls declaradas en applications.departamento.urls.py a 'http://127.0.0.1:8000/XXXXXXXX/'
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# from django.contrib import admin
# from django.urls import path

# def PruebaUrl(self):
#     print("********************************* Hola Testing URLS*****************************")
    
# urlpatterns = [
#     path('admin/', admin.site.urls), # Django ejecutara admin.site.urls si en el navegador colocamos la cadena 'http://127.0.0.1:8000/admin/'
#     path('prueba/', PruebaUrl), # Django ejecutara PruebaUrl si en el navegador colocamos la cadena 'http://127.0.0.1:8000/prueba/'
# ]

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <!-- <a href="/listar-todo-empleados">Listar</a> -->
          <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
          <!-- <ul class="menu vertical"> -->
            <!-- <li><a href="#">A</a></li>
            <li><a href="#">B</a></li>
            <li><a href="#">CThree</a></li> -->
          <!-- </ul> -->
        </li>
        <li><a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <a class="button success" href="{% url 'persona_app:empleado_add' %}">Regisrar Nuevo</a>
        <!-- <li><button type="button" class="button">Regisrar Nuevo</button></li> -->
      </ul>
    </div>
  </div>


  