empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

# def DesdeAppPersona(self):
#     print('###############################Desde la App Persona######################################' )
    
# urlpatterns = [
#     path('persona/', DesdeAppPersona), # Django ejecutara la funcion DesdeAppDepartamento si en el navegador colocamos la cadena 'http://127.0.0.1:8000/persona/'
# ]

from . views import (ListAllEmpleados,ListByArea,ListByJob,
                    ListEmpleadosByKword,ListHabilidadesEmpleado,
                    EmpleadoDetailView,EmpleadoCreateView,
                    SuccessView,EmpleadoUpdateView,
                    EmpleadoDeleteView,
                    InicioView,
                    ListEmpleadosAdmin

)

app_name = "persona_app" # este es una etiqueta para ubicar el bloque urls de la aplicacion persona

urlpatterns = [
    path('',InicioView.as_view(),name='inicio'),
    path('buscar_empleado/', ListEmpleadosByKword.as_view(),name='buscar_empleado'), # Django ejecutara PruebaView(TemplateView) si en el navegador colocamos la cadena 'http://127.0.0.1:8000/prueba/'
    path('listar-todo-empleados/', ListAllEmpleados.as_view(),name='empleados_all'), # Django ejecutara ListAllEmpleados(ListView) si en el navegador colocamos la cadena 'http://127.0.0.1:8000/listar-todo-empleados/'
    path('lista_by_area/<shor_name>/',ListByArea.as_view(),name='empleados_area'),
    path('lista_by_job/',ListByJob.as_view()),
    path('lista_habilidades_empleado/',ListHabilidadesEmpleado.as_view()),
    path('ver_empleado/<pk>/',EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/',EmpleadoCreateView.as_view(), name='empleado_add'),
    # path('success/',SuccessView.as_view()),
    path(
        'success/',SuccessView.as_view(),
        name='correcto'      #con name puedo hacer mencion a la url "/success" desde cualquier success_url
    ),                           
    path('update_empleado/<pk>/',EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('eliminar_empleado/<pk>/',EmpleadoDeleteView.as_view(),name='eliminar_empleado'),
    path('lista_empleados_admin/',ListEmpleadosAdmin.as_view(),name='empleados_admin'),
        
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

    
urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluiremos las urls de la app departamento
    path('', include('applications.departamento.urls')), # Django incluye las diferentes urls declaradas en applications.departamento.urls.py a 'http://127.0.0.1:8000/XXXXXXXX/'
    path('', include('applications.persona.urls')), # Django incluye las diferentes urls declaradas en applications.departamento.urls.py a 'http://127.0.0.1:8000/XXXXXXXX/'
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# from django.contrib import admin
# from django.urls import path

# def PruebaUrl(self):
#     print("********************************* Hola Testing URLS*****************************")
    
# urlpatterns = [
#     path('admin/', admin.site.urls), # Django ejecutara admin.site.urls si en el navegador colocamos la cadena 'http://127.0.0.1:8000/admin/'
#     path('prueba/', PruebaUrl), # Django ejecutara PruebaUrl si en el navegador colocamos la cadena 'http://127.0.0.1:8000/prueba/'
# ]

empleado/applications/persona/models.py
from django.db import models
from django.db.models.fields.files import ImageField, ImageFieldFile
from django.db.models.fields.related import ForeignKey
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Creamos la tabla Habilidades
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50,unique=True)

    class Meta:
        verbose_name = "Habilidad"
        verbose_name_plural ='Habilidades del personal'

    def __str__(self):  
        """Unicode representation of Departamento"""
        return str(self.id) + "-"  + self.habilidad # cuando pidan empleado.habilidades voy a mandar id - habilidad, si solo quieren la
                                                    # habilidad deben pedir elemento.habilidades.habilidad
        



""" Modelo para la tabla empleado"""
class Empleado(models.Model):
    job_choices = (
        ('0','Contador'),
        ('1','Administrador'),
        ('2','Economista'),
        ('3','Analista'),
        ('4','Otros'),
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombres_completos', max_length=120,blank=True)
    job = models.CharField('Trabajo', max_length=1,choices=job_choices)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    #avatar = models.ImageField(, upload_to='empleado', height_field=None, width_field=None, max_length=None)
    avatar = models.ImageField(upload_to='empleado', blank=True,null=True)
    habilidades = models.ManyToManyField(Habilidades) # el argumento Habilidades es la tabla con la que hay una relacion many-to-many
    hoja_vida = RichTextField()

    class Meta: # Esta clase la definimos para personalizar la presendacion en el Django administrator (127.0.0.1:8000/admin/)
        verbose_name = "Nombre del empleado"
        verbose_name_plural ='Empleados nacionales'
        ordering = ['last_name','first_name']
            
    def __str__(self):
        """Unicode representation of persona"""
        return str(self.id) + ' / ' + self.first_name + ' / ' + self.last_name + ' / ' + self.job

empleado/applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = (            # los fields nos permite mostrar los campos que queramos mostrar en la pagina .html
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )

        widgets = {
            'habilidades' : forms.CheckboxSelectMultiple()
        }

empleado/applications/persona/views.py
from typing import Collection
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView,
    CreateView,TemplateView,
    UpdateView,DeleteView
)
from .models import Empleado
from django.http import HttpResponseRedirect
from .forms import EmpleadoForm

class InicioView(TemplateView):
    ''' Vista de carga la hoja de inicio'''
    template_name = "inicio.html"


# listar todos los empleado de la empresa
class ListAllEmpleados(ListView):
    # Dato curioso intencionalmente elimine template_name, por defecto buscara el archivo templates.persona.empleado_list.html
    #template_name = "persona/empleado_list.html"
    template_name = "persona/lista_all.html"
    paginate_by = 4  # para ver la pagina 3 hacemos 127.0.0.1:800/listar-todo-empleados/?page=3
                     # Cuando ListView se encuentra un paginate_by automaticamente crea un objeto paginator
    ordering = 'first_name'
    # model = Empleado  # inhabilito esta linea porque voy a usar el metodo get_queryset y no tengo qque especificar el modelo aqui.
    #context_object_name = 'lista'  # no es necesario porque ya ListView provee self.object_list disponible en una pagina html mediante  {{object_list}}

    # Esto me lo copie de la class ListEmpleadosByKword para buscar un empleado desde la html: http://127.0.0.1:8000/listar-todo-empleados/
    def get_queryset(self):
        # print('#################')
        palabra_clave = self.request.GET.get("kword", '') # request es un object que contiene las solicitudes que se han enviado a un servidor
                                                          #Interceptamos el metodo GET. Django ha ordenado internamente en metodos y submetodos
                                                          # recuperame (get) el valor con el identificador 'kword' . Esto debe ser una tupla  
        
        # lista = Empleado.objects.filter(
        #     # departamento__name = 'Ventas al detal'
        #     #departamento__name = area
        #     #first_name = palabra_clave
        #     last_name = palabra_clave
        # )
        
        lista = Empleado.objects.filter(full_name__icontains=palabra_clave)

        print('lista filtrada: ', lista)
        return lista


# Listar empleados desde el menu Administracion
class ListEmpleadosAdmin(ListView):
    template_name = "persona/lista_empleados.html"
    paginate_by = 10  # para ver la pagina 3 hacemos 127.0.0.1:800/listar-todo-empleados/?page=3
                     # Cuando ListView se encuentra un paginate_by automaticamente crea un objeto paginator
    ordering = 'first_name'
    model = Empleado  # inhabilito esta linea porque voy a usar el metodo get_queryset y no tengo qque especificar el modelo aqui.
    context_object_name = 'lista'  # no es necesario porque ya ListView provee self.object_list disponible en una pagina html mediante  {{object_list}}

   

# listar todos los empleados que pertenecen a un area de la empresa
class ListByArea(ListView):
    #model = Empleado
    template_name = "persona/list_by_area.html"
    context_object_name = 'empleados'
    # queryset = Empleado.objects.filter(
    #     departamento__name = 'Control administrativo'
    # )

    def get_queryset(self):
        """
        Return the list of items for this view.
        The return value must be an iterable and may be an instance of
        `QuerySet` in which case `QuerySet` specific behavior will be enabled.
        """
        area = self.kwargs['shor_name'] # kwargs (keyword arguments)es un metodo de django para recoger lo que envien por url
        queryset = Empleado.objects.filter(
            # departamento__name = 'Ventas al detal'
            #departamento__name = area
            departamento__shor_name = area
        )
        return queryset 




#####################################################################################

# listar todos los empleados que pertenecen a un cargo en particular en la empresa 

class ListByJob(ListView):
    template_name = "persona/list_by_job.html"
    model = Empleado
    context_object_name ='empleados'
    def get_queryset(self):
        job = self.request.GET.get("job", '')
        print(job)
        empleado = Empleado.objects.filter(job=job)  # revisar https://docs.djangoproject.com/en/3.2/topics/db/queries/
        print(empleado)
        return empleado
      
      

#######################################################################################


# Listar empleados por palabra clave
class ListEmpleadosByKword(ListView):
    template_name = "persona/by_kword.html"
    #model = MODEL_NAME
    context_object_name ='empleados'
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '') # request es un object que contiene las solicitudes que se han enviado a un servidor
                                                          #Interceptamos el metodo GET. Django ha ordenado internamente en metodos y submetodos
                                                          # recuperame (get) el valor con el identificador 'kword' . Esto debe ser una tupla  
        
        lista = Empleado.objects.filter(
            # departamento__name = 'Ventas al detal'
            #departamento__name = area
            #first_name = palabra_clave
            last_name = palabra_clave
        )
        print('lista filtrada: ', lista)
        return lista
        
##########################################################################################

class ListHabilidadesEmpleado(ListView):
    template_name = "persona/habilidades.html"
    context_object_name ='habilidades'
    def get_queryset(self):
        id = self.request.GET.get('id', '')
        print(id)
        empleado = Empleado.objects.get(id=id)        
        #print(empleado.habilidades.all())
        return empleado.habilidades.all()
        
#########################################################################################
    
class EmpleadoDetailView(DetailView):
    model = Empleado             
    template_name = "persona/detail_empleado.html" # en este file podemos llamar {{object}} o {{empleado}} ojo: en minuscula
                                                   # y sus atributos, por ejemplo object.first_name   {{object.first_name}}
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView,self).get_context_data(**kwargs)
        print(context)
        # Bloque que representa la determinacion
        #          del empleado del mes
        dedicacion = 4/5
        planificacion = 5/5
        responsabilidad = 4/5
        compromiso = 4/5
        a = dedicacion + planificacion + responsabilidad + compromiso
        context['titulo'] = 'Empleado del mes'
        context['a'] = a
        return context

####################################################################


class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    template_name = "persona/add.html"
    model = Empleado  #
    #fields = ('__all__')
    # fields = ['first_name','last_name','job','departamento', 'habilidades','avatar']  # ya no necesito los fields porque voy a trabajar con formularios
    form_class = EmpleadoForm  # ahora el modelo de formulario EmpleadoForm define los fields que mostrare en los html

    #success_url = '.'  # The URL to redirect to after successful registration. A string containing a (relative) URL, or a string
                       #  name of a URL pattern, or a 3-tuple of arguments suitable for passing to Django’s redirect shortcut. 
                       # Can be overridden on a per-request basis (see below). Default value is None, so that per-request customization is used instead.
                       # '.' nos recarga la misma pagina, es decir add.html
    
    #success_url = '/success'  # con esto redirecciono a la url definida en  path('success/',SuccessView.as_view()),
                               # esta forma de redireccionar no es muy elegante. La alternativa es reverse_lazy disponile en django.urls
    # success_url = reverse_lazy('persona_app:correcto') # atencion - No debe haer espacios en blanco, Django lo consideraria como una cadena con espacio
    success_url = reverse_lazy('persona_app:empleados_admin')
    # vamos a interceptar la creacion de un nuevo empleado sobre escribiendo la clase EmpleadoCreateView
    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        #self.object = form.save()
        #print(self.object)
        empleado = form.save(commit=False) # Commit=False para que no salve, me permite modificar algo antes de salvar
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        print(empleado.full_name)
        empleado.save()        
        return super(EmpleadoCreateView,self).form_valid(form)
        
####################################################################


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/update.html"
    model = Empleado
    # fields = ['first_name','last_name','job','departamento', 'habilidades']
    form_class = EmpleadoForm
    # success_url = reverse_lazy('persona_app:correcto')
    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        # empleado = self.get_object()
        print('#########################  METODO POST  ############################')
        print('#####################################################################')
        # print(request.POST)
        print(
            request.POST['first_name'],request.POST['last_name'],
            request.POST['job'],request.POST['departamento'],
            request.POST['habilidades']
            )
        return super(EmpleadoUpdateView,self).post(request, *args, **kwargs)

    def form_valid(self, form):

empleado/templates/persona/add.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Pagina de actualizacion de empleados{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar empleado</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres
                        {{ form.first_name }}
                      
                    </label>
                  </div>
                  <div class="medium-6 cell">
                    <label>Apellidos
                        {{ form.last_name }}
                    </label>
                  </div>
                  <div class="medium-6 cell">
                    <label>Trabajo
                        {{ form.job }}
                     
                    </label>
                  </div>
                  <div class="medium-6 cell">
                    <label>Departamento
                        {{ form.departamento }}
                      
                    </label>
                  </div>
                  <div class="medium-6 cell">
                    <label>Habilidades
                        {{ form.habilidades }}
                                       
                    </label>
                  </div>

                  <div class="medium-6 cell">
                    <label>Foto
                        {{ form.avatar }}
                                       
                    </label>
                  </div>

                  <div class="cell">
                    <button type="submit" class="success button">Guardar</button>

                  </div>
                    
            </form>

        </div>

    </div>

</div>

{% endblock content %}
    








<!-- <h1> Registro de empleados o contratistas</h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Agregar">
</form> -->

empleado/templates/persona/by_kword.html
<h1> Buscar empleados por palabra clave </h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui" >
    <button type="submit">Buscar</button>
</form>
<h3>Lista resultados</h3>

<ul>
    
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

empleado/templates/persona/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Eliminar empleado{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{object.full_name}}</h1>
        <form class="cell" method="post"> {% csrf_token %}
            <div class="callout">
                <h5>Desea eliminar a este empleado?</h5>
                <p>Su borrado sera definitivo y no podra ser recuperado</p>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
            


        </form>
    

    </div>


</div>

{% endblock content %} 



<!-- <h1> Eliminar empleado</h1>

<form method="post"> {% csrf_token %}

    <p>Confirmar que desea eliminar este registro</p>

    <button type="submit">Confirmar</button

</form> -->

   

empleado/templates/persona/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ object.full_name}}{% endblock title %}
{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell large-4 card" style="width: 350px; margin-top: 10px;">
      <div class="card-divider">
        <!-- {{empleado.job}} -->
      
        {% if empleado.avatar %}
        <img src="{{ empleado.avatar.url }}">
        {% else %}
        <img src="{% static 'img/face_not_found.jpg' %}">
        
        {% endif %}
          
      </div>
      
      <div class="card-section">
        <h4>{{ empleado.full_name }}</h4>
        <p>{{ empleado.get_job_display }}</p>  
        <p>{{ empleado.departamento }}</p>
        <p>{{ empleado.departamento.shor_name }}</p>
        <p><span class="label">Habilidades</span></p>
        <ul class="vertical menu">
          {% for h in empleado.habilidades.all %}
          
            <li>{{ h.habilidad }}</li>
            
            {% endfor %}
            

        </ul>
      </div>
    </div>
  
  </div>
  
</div>





<!-- <table>
     <thead>
       <tr>
         <th width="50">Nombre</th>
         <th width="50">Apellido</th>
         <th width="150">Cargo</th>
         <th width="150">Departamento</th>
         <th width="150">Habilidades</th>
       </tr>
     </thead>
     <tbody>
       <tr>
         <td>{{empleado.first_name}}</td>
         <td>{{empleado.last_name}}</td>
         <td>{{empleado.job}}</td>
         <td>{{empleado.departamento}}</td>
         <td>{{empleado.habilidades}}</td>
       </tr>
       
     </tbody>
   </table>
 -->




{% endblock content %}
     

<!-- <h1> Detalle del empleado  {{titulo}} </h1>
<li> <br>{{object}}
     <br>{{empleado}}
</li>

<h3>Todos los datos</h3>
<p>{{empleado.first_name}}</p>
<p>{{empleado.last_name}}</p>
<p>{{empleado.job}}</p>
<p>{{empleado.departamento}}</p>
<p>{{empleado.habilidades}}</p>
<p>{{empleado.hoja_vida}}</p>


<p>El valor obtnido en la evaluacion es : {{a}} /5 </p> -->

empleado/templates/persona/empleado_list.html
<h1>ListAllEmpleados busca el archivo empleado_list.html</h1>


<ul>
    
    {% for e in object_list %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

empleado/templates/persona/habilidades.html
<h1> Habilidades del empleado</h1>

<form method="GET">{% csrf_token %}
    <input type="int" id=id name=id placeholder="Ingrese el Id del empleado" >
    <button type="submit">Buscar</button>
</form>

<ul>
  
    {% for e in habilidades %}
       <li>
        {{e}}

       </li> 
    {% endfor %}
        
  </ul>

empleado/templates/persona/list_by_area.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% block title %} Lista de empleados por departamneto{% endblock title %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">Empleados adscritos a este departamento</div>
          <div class="cell">
            <table>
              <tbody>
                  {% for e in empleados %}
                  <tr>
                      <td>{{ e.first_name }}</td>
                      <td>{{ e.last_name }}</td>
                      <td>{{ e.job }}</td>
                      <td>{{ e.departamento }}</td>
                      
                  {% endfor %}
                  </tr>
              </tbody>
          </table>
            
          </div>

           

        </div>
    </div>
   
</div>

{% endblock content %}
    




<!-- <h1>Lista empleados por departamento</h1>

{{object_list}}

<ul>
  
  {% for e in object_list %}
      {{e}}
  {% endfor %}
      
</ul>


<ul>
  
    {% for e in object_list %}
       <li>
        {{e}}

       </li> 
    {% endfor %}
        
  </ul> -->

empleado/templates/persona/list_by_job.html
<h1>  Listado por cargo</h1>

<li>

    Marque  0   :Contador
            1   :Administrador
            2   :Economista
            3   :Analista
            4   :Otros
  
</li>


<form method="GET">{% csrf_token %}
    <input type="int" id=job name=job placeholder="Ingrese cargo aqui" >
    <button type="submit">Buscar</button>
</form>

<ul>
  
    {% for e in empleados %}
       <li>
        {{e}}

       </li> 
    {% endfor %}
        
  </ul>

empleado/templates/persona/lista_all.html
{% extends 'base.html' %}  

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de empleados</h1>
        <!-- <div class="cell grid-x grid-margin-x"> -->
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %} 
            <div class="cell large-7" >
                <!-- <input type="text" placeholder="Buscar empleado"> lo inhailito porque el input yel button tienen que estar dentro de un loque for cuando usamos una peticion GET al servidor-->
                <input type="text" name="kword" id="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-5" >
                <!-- <button type="button" class="success button">Buscar</button>              -->
                <button type="submit" class="success button">Buscar></button>
            </div>
        <!-- </div> -->
        </form>
        <div class="cell">
            
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="200">APELLIDOS</th>
                    <th width="200">DEPARTAMENTO</th>
                    <th width="200">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td> 
                    </tr>
                    {% endfor %}
                  </tr>
                </tbody>
            </table>
                        
        </div>

    </div>
    <div class="cell">
        <!-- {% if is_paginated %} -->
        <nav aria-label="Pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                </li> 
                {% endif %}
        
                {% for pag in paginator.page_range %}
                
                {% ifequal pag page_obj.number  %}
                <!-- <li class="current"><span class="show-for-sr">You're on page</span>{{ pag }}</li> -->
                <li class="current">{{ pag }}</li>
                {% else %}
                <li><a href="?page={{ pag }}" >{{ pag }}</a></li>
                {% endifequal %}
                    

                
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="Pagination-next"><a href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
                {% endif %}
            </ul>
        </nav>
            
        {% endif %}
            
        
    </div>

</div>
{% endblock content %} 



<!-- <h1>Prueba Listar_todo_empleados</h1>

<ul>
    
    {% for e in object_list %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul> -->

empleado/templates/persona/lista_empleados.html
{% extends 'base.html' %}  

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de empleados</h1>
        <!-- <div class="cell grid-x grid-margin-x"> -->
        
        <div class="cell">
            
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="200">APELLIDOS</th>
                    <th width="200">DEPARTAMENTO</th>
                    <th width="200">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td>
                            <a class="button warning" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                            <a class="button warning" href="{% url 'persona_app:eliminar_empleado' e.id  %}">Eliminar</a>
                        </td> 
                    </tr>
                    {% endfor %}
                  </tr>
                </tbody>
            </table>
                        
        </div>

    </div>
    <div class="cell">
        <!-- {% if is_paginated %} -->
        <nav aria-label="Pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                </li> 
                {% endif %}
        
                {% for pag in paginator.page_range %}
                
                {% ifequal pag page_obj.number  %}
                <!-- <li class="current"><span class="show-for-sr">You're on page</span>{{ pag }}</li> -->
                <li class="current">{{ pag }}</li>
                {% else %}
                <li><a href="?page={{ pag }}" >{{ pag }}</a></li>
                {% endifequal %}
                    

                
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="Pagination-next"><a href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
                {% endif %}
            </ul>
        </nav>
            
        {% endif %}
            
        
    </div>

</div>
{% endblock content %} 

empleado/templates/persona/success.html
<h1>Felicitaciones. La operacion fue ejecutada satisfactoriamente</h1>