empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

def DesdeAppDepartamento(self):
    print('###############################Desde la App Departamento######################################' )

app_name = "departamento_app"

urlpatterns = [
    path('departamento/', DesdeAppDepartamento), # Django ejecutara la funcion DesdeAppDepartamento si en el navegador colocamos la cadena 'http://127.0.0.1:8000/departamento/'
    path('new_departamento/', views.NewDepartamentoView.as_view(),name='nuevo_departamento'),
    path('departamento_lista/', views.DepartamentoListView.as_view(),name='departamento_list'),

]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

# def DesdeAppPersona(self):
#     print('###############################Desde la App Persona######################################' )
    
# urlpatterns = [
#     path('persona/', DesdeAppPersona), # Django ejecutara la funcion DesdeAppDepartamento si en el navegador colocamos la cadena 'http://127.0.0.1:8000/persona/'
# ]

from . views import (ListAllEmpleados,ListByArea,ListByJob,
                    ListEmpleadosByKword,ListHabilidadesEmpleado,
                    EmpleadoDetailView,EmpleadoCreateView,
                    SuccessView,EmpleadoUpdateView,
                    EmpleadoDeleteView,
                    InicioView,
                    ListEmpleadosAdmin

)

app_name = "persona_app" # este es una etiqueta para ubicar el bloque urls de la aplicacion persona

urlpatterns = [
    path('',InicioView.as_view(),name='inicio'),
    path('buscar_empleado/', ListEmpleadosByKword.as_view(),name='buscar_empleado'), # Django ejecutara PruebaView(TemplateView) si en el navegador colocamos la cadena 'http://127.0.0.1:8000/prueba/'
    path('listar-todo-empleados/', ListAllEmpleados.as_view(),name='empleados_all'), # Django ejecutara ListAllEmpleados(ListView) si en el navegador colocamos la cadena 'http://127.0.0.1:8000/listar-todo-empleados/'
    path('lista_by_area/<shor_name>/',ListByArea.as_view(),name='empleados_area'),
    path('lista_by_job/',ListByJob.as_view()),
    path('lista_habilidades_empleado/',ListHabilidadesEmpleado.as_view()),
    path('ver_empleado/<pk>/',EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/',EmpleadoCreateView.as_view(), name='empleado_add'),
    # path('success/',SuccessView.as_view()),
    path(
        'success/',SuccessView.as_view(),
        name='correcto'      #con name puedo hacer mencion a la url "/success" desde cualquier success_url
    ),                           
    path('update_empleado/<pk>/',EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('eliminar_empleado/<pk>/',EmpleadoDeleteView.as_view(),name='eliminar_empleado'),
    path('lista_empleados_admin/',ListEmpleadosAdmin.as_view(),name='empleados_admin'),
        
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

    
urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluiremos las urls de la app departamento
    path('', include('applications.departamento.urls')), # Django incluye las diferentes urls declaradas en applications.departamento.urls.py a 'http://127.0.0.1:8000/XXXXXXXX/'
    path('', include('applications.persona.urls')), # Django incluye las diferentes urls declaradas en applications.departamento.urls.py a 'http://127.0.0.1:8000/XXXXXXXX/'
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# from django.contrib import admin
# from django.urls import path

# def PruebaUrl(self):
#     print("********************************* Hola Testing URLS*****************************")
    
# urlpatterns = [
#     path('admin/', admin.site.urls), # Django ejecutara admin.site.urls si en el navegador colocamos la cadena 'http://127.0.0.1:8000/admin/'
#     path('prueba/', PruebaUrl), # Django ejecutara PruebaUrl si en el navegador colocamos la cadena 'http://127.0.0.1:8000/prueba/'
# ]

empleado/applications/departamento/models.py
from django.db import models

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50,editable=True)
    shor_name = models.CharField('Nombre Corto', max_length=50,unique=True)
    anulate = models.BooleanField('Anulado', default=False)


    class Meta: # Esta clase la definimos para personalizar la presendacion en el Django administrator (127.0.0.1:8000/admin/)
        verbose_name = "Nombre del Departamento"
        verbose_name_plural ='Departamentos de la empresa'
        ordering = ['name']
        unique_together = ('name', 'shor_name') 
    
    def __str__(self):
        """Unicode representation of Departamento"""
        return self.name + ' / ' + self.shor_name

empleado/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre_encargado = forms.CharField(max_length=50, required=True)   # nombre: nombre del empleado a cargo del departamento a crear
    apellidos_encargado = forms.CharField(max_length=50, required=True)  # required=True es equivalente a no ponerlo, es decir es obligatorio
    nombre_departamento = forms.CharField(max_length=30)
    short_name_dpto = forms.CharField(max_length=20)
     

empleado/applications/departamento/views.py
from applications import departamento
from django.shortcuts import render
from django.views.generic.edit import FormView
from .forms import NewDepartamentoForm
from applications.persona.models import Empleado
from .models import Departamento

from django.views.generic import ListView



class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    # paginate_by = 4
    context_object_name = 'departamento' # esto lo hago para utilizar departamento en lugar de object_list en el archivo html
                                         # si no declaro la variale context_object_name tendre que usar object_list en el archivo html 


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'
  
    def form_valid(self, form):

        departamento_creado = Departamento(
        name = form.cleaned_data['nombre_departamento'],
        shor_name = form.cleaned_data['short_name_dpto']
    )
        departamento_creado.save()

        """If the form is valid, save the associated departamento."""
        print('######################### departamento  FORM_VALID  ############################')
        nombre_encargado = form.cleaned_data['nombre_encargado']
        apellidos_encargado = form.cleaned_data['apellidos_encargado']
        Empleado.objects.create(
            first_name=nombre_encargado,
            last_name=apellidos_encargado,
            job='1',
            departamento = departamento_creado
        )
   
        return super(NewDepartamentoView,self).form_valid(form)

class ListAllDepartamentos(ListView):
    # Dato curioso intencionalmente elimine template_name, por defecto buscara el archivo templates.persona.empleado_list.html
    #template_name = "persona/empleado_list.html"
    template_name = "departamento/lista_all.html"
    paginate_by = 4  # para ver la pagina 3 hacemos 127.0.0.1:800/listar-todo-empleados/?page=3
                     # Cuando ListView se encuentra un paginate_by automaticamente crea un objeto paginator
    ordering = 'name'
    # model = Empleado  # inhabilito esta linea porque voy a usar el metodo get_queryset y no tengo qque especificar el modelo aqui.
    #context_object_name = 'lista'  # no es necesario porque ya ListView provee self.object_list disponible en una pagina html mediante  {{object_list}}

    # Esto me lo copie de la class ListEmpleadosByKword para buscar un empleado desde la html: http://127.0.0.1:8000/listar-todo-departamentos/
    def get_queryset(self):
        # print('#################')
        palabra_clave = self.request.GET.get("kword", '') # request es un object que contiene las solicitudes que se han enviado a un servidor
                                                          #Interceptamos el metodo GET. Django ha ordenado internamente en metodos y submetodos
                                                          # recuperame (get) el valor con el identificador 'kword' . Esto debe ser una tupla  
        
        # lista = Empleado.objects.filter(
        #     # departamento__name = 'Ventas al detal'
        #     #departamento__name = area
        #     #first_name = palabra_clave
        #     last_name = palabra_clave
        # )
        
        lista = Departamento.objects.filter(name__icontains=palabra_clave)

        print('lista filtrada: ', lista)
        return lista

empleado/templates/departamento/lista.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% block title %} Lista de Departamentos de la empresa{% endblock title %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Departamentos</h1>
        <div class="cell">

            <table>
                <tbody>
                    {% for d in departamento %}
                    <tr>
                        <td>{{ d.name }}</td>
                        <td>{{ d.shor_name }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleados_area' d.shor_name %}">Ver empleados</a></td> 
                        {% endfor %}
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
   
</div>

{% endblock content %}
    














    

empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/header.html' %}

{% block title %} Pagina de Creacion de nuevo Departamento{% endblock title %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
            <form class="cell callout grid-x grid-margin-x" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombre del Departamento
                        {{form.nombre_departamento}}
                    </label>
                   
                </div>
                <div class="cell large-6">
                    <label>Nombre corto del Departamento
                        {{form.short_name_dpto}}
                    </label>

                </div>
                <div class="cell large-6">
                    <label>Nombre del encrgado del Departamento
                        {{form.nombre_encargado}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos del encrgado del Departamento
                        {{form.apellidos_encargado}}
                    </label>

                </div>

                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>

                  </div>


            </form>

        </div>


    </div>

</div>


{% endblock content %}







<!-- <h1>Crear nuevo Departamento</h1>

<form method="POST">{% csrf_token %}
    <h3>Datos del empleado en cargo del Departamento</h3>
    <p>Nombre
        {{form.nombre_encargado}}
    </p>
    <p>Apellido
        {{form.apellidos_encargado}}
    </p>
    <h3>Datos del Departamento a crear</h3>
    <p>Nombre
        {{form.nombre_departamento}}
    </p>
    <p>Nombre corto
        {{form.short_name_dpto}}
    </p>
    <button type="submit">Guardar</button>

</form> -->